name: main
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.4.1+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter_localizations:
    sdk: flutter
  flutter:
    sdk: flutter
  json_annotation: ^4.8.1
  http: ^1.2.2

dev_dependencies:
  json_serializable: ^6.7.1
  flutter_test:
    sdk: flutter
  flutter_gen_runner:
  build_runner:

  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"
  remove_alpha_ios: true
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter:
  generate: true
  uses-material-design: true

#  assets:
#    - assets/
#    - assets/icons/

flutter_gen:
  output: lib/generated/
  line_length: 80

  integrations:
    flutter_svg: true

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
flutter_intl:
  enabled: true